[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview]
hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL

[context.deploy-preview.environment]
HUGO_VERSION="0.74.3"

[context.production.environment]
HUGO_VERSION="0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
